---
title: "Age-related transcriptional profiling of phagocytic cells from mice eWAT"
author: "martinnwadiugwu"
date: "4/8/2021"
output:
  pdf_document: default
  html_document: default
---

```{r Data manipulation, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Obtaining data
ReadData = read.csv(file = 'Assignment 2.txt', sep = '\t')
ReadData = data.frame(as.factor(ReadData$GeneSymbol), as.factor(ReadData$Gene_Type), round(ReadData$length), round(ReadData$eff_length), round(ReadData$GSM4681350_eWAT_phagocytic_SVF_2m_male.kallisto_res.abundance.tsv), round(ReadData$GSM4681354_eWAT_phagocytic_SVF_2m_male.kallisto_res.abundance.tsv), round(ReadData$GSM4681352_eWAT_phagocytic_SVF_20m_male.kallisto_res.abundance.tsv), round(ReadData$GSM4681356_eWAT_phagocytic_SVF_20m_male.kallisto_res.abundance.tsv))

#Rename column names
names(ReadData)[1] <- "GeneSymbol"
names(ReadData)[2] <- "Gene_Type"
names(ReadData)[3] <- "lenght"
names(ReadData)[4] <- "eff_lenght"
names(ReadData)[5] <- "GSM4681350_eWAT_phagocytic_SVF_2m_male"
names(ReadData)[6] <- "GSM4681354_eWAT_phagocytic_SVF_2m_male"
names(ReadData)[7] <- "GSM4681352_eWAT_phagocytic_SVF_20m_male"
names(ReadData)[8] <- "GSM4681356_eWAT_phagocytic_SVF_20m_male"

#Removing unwanted colunms
ReadData[,c(2,3,4)]  = NULL


#Aggregating data

ReadAggExp = aggregate(x = ReadData[,2:5], by = list(ReadData$GeneSymbol), FUN = sum)
names(ReadAggExp)[1] <- "GeneSymbol"

#Phenodata
my_pheno = data.frame(row.names = colnames(ReadAggExp)[-1], Age = c(2,2,20,20) )
```


#### RNA-seq - DEseq2 usage example
#BiocManager::install("DESeq2")

```{r RNA-seq analysis}

library("DESeq2")

# filter low coverage genes (>=5 counts) 
ReadAggExp1 = data.frame(row.names = (ReadAggExp)[,1], ReadAggExp[-1] )

ReadAggExp2 <- ReadAggExp1[rowSums(ReadAggExp1) >= 5,]
                      
                      
# create DESeq2 object

dds <- DESeqDataSetFromMatrix(countData = ReadAggExp2,
                              colData = my_pheno,
                              design = ~ Age)

# run DEseq2 algorithm
dds <- DESeq(dds)

# extract DEseq2 results
res <- results(dds, name = "Age") #if instead contrast is used = c("young", "aged"))
res

#library(Glimma)
#glimmaMA(dds)

save(res, file = "Extracted_DEseq2_result.RData")

# load("Extracted_DEseq2_result.RData")  #### load for expediency

#writing to csv file ALL genes DESeq2 tested 
DEG = write.csv(data.frame(res), "DEG.csv")

```


###Data exploration using pvclust and MDS

```{r Data exploration}
### PVclust - hierarchical clustering with bootstrap resampling
###################################################################################################################
library('pvclust')

#VST normalization
vsd =getVarianceStabilizedData(dds)


# call clustering function, enter desired clustering parameters
# For REAL analysis: 100 or more bootstraps!!!!
result.pvclust <- pvclust(na.omit(vsd[,-1]), nboot = 1000)

# plot results to screen: how are replicates clustering?
plot(result.pvclust)

# plot results to external pdf
pdf(paste(Sys.Date(),"GSE154832_pvclust_eWAT_data.pdf",sep="_"))
plot(result.pvclust)
dev.off()


################################################################################################ 4. Multidimensional dimensional scaling analysis(MDS)
#############################################################################################

# do MDS analysis
mds.result <- cmdscale(1-cor(vsd[,-(1)],method="spearman"), k = 2, eig = FALSE, add = FALSE, x.ret = FALSE)

x <- mds.result[, 1]
y <- mds.result[, 2]

my.pch <- c(rep(16,2), rep(17,2))
my.colors.age <- c(rep("coral",1), rep("cyan",1)) 

pdf(paste(Sys.Date(),"GSE154832_MDS_plot.pdf",sep="_"))
plot(x, y,
     pch = my.pch, col = my.colors.age,
     xlab = "MDS dimension 1", ylab = "MDS dimension 2",
     main="Multi-dimensional Scaling",cex=2)
legend("topright", c("young","Aged"), col = "grey", pch = c(16,17), bty = 'n', pt.cex = 2)
legend("bottomright", c("2m","20m"), col = c("coral","cyan"), pch = 15, bty = 'n', pt.cex = 2)
dev.off()

```

###### Functional enrichment with Clusterprofiler
# BiocManager::install("clusterProfiler")
#BiocManager::install('org.Mm.eg.db') for mus Musculus


```{r Functional enrichment analysis}

library("clusterProfiler")

# key types access and ID conversion
library(org.Mm.eg.db)
keytypes(org.Mm.eg.db)

# convert gene names to other IDs
ids <- bitr(rownames(ReadAggExp2),
            fromType="SYMBOL", 
            toType=c("UNIPROT", "ENSEMBL"), 
            OrgDb="org.Mm.eg.db")
ids

# Expressed/detected genes (universe)
bckgd <- bitr(rownames(res), fromType="SYMBOL",
              toType="ENTREZID", OrgDb="org.Mm.eg.db")



##### prep data for analysis with ClusterProfiler for gene set enrichment analysis[GSEA]

# create ranked geneList object, Necessary for GSEA type analysis
# GeneList data format from DOSE package
# use t-statistic (or LogFC) to rank genes

res$GeneSymbol <- rownames(res) # GeneSymbol
my.merged.names <- merge(data.frame(res), bckgd, by.x = "GeneSymbol", by.y = "SYMBOL")# get ENTREZ (necessary for KEGG)

res.geneList = my.merged.names$stat #moderated t stat from DEseq2
res.geneListFC = my.merged.names$log2FoldChange #moderated t stat from DEseq2

names(res.geneList) = as.character(my.merged.names$ENTREZID)  #gene names
res.geneList = sort(res.geneList, decreasing = TRUE)  #rank/sort


# GO Gene Set Enrichment Analysis (with p-value =1)
ego3 <- gseGO(geneList     = res.geneList,
              OrgDb        = org.Mm.eg.db,
              keyType      = "ENTREZID",
              ont          = "BP",
              nPerm        = 10000,                     #10k in real life
              minGSSize    = 50,                       #5-50 in real life
              maxGSSize    = 3000,                     #>2500 in real life
              pvalueCutoff = 1,                      #0.05 in real life (usually)
              verbose      = FALSE)

#writing to csv file 
DEG_gseGO_BP_NoSig = write.csv(data.frame(ego3), "DEG_gseGO_BP_ALL.csv")

head(ego3)



# GO-BP Gene Set Enrichment Analysis (with p-value =0.05)
ego2.1 <- gseGO(geneList     = res.geneList,
              OrgDb        = org.Mm.eg.db,
              keyType      = "ENTREZID",
              ont          = "BP",
              nPerm        = 10000,                     #10k in real life
              minGSSize    = 50,                       #5-50 in real life
              maxGSSize    = 3000,                     #>2500 in real life
              pvalueCutoff = 0.05,                      #0.05 in real life (usually)
              verbose      = FALSE)


#writing to csv file 
DEG_gseGO_BP = write.csv(data.frame(ego2.1), "DEG_gseGO_BP.csv")

# GO-CC Gene Set Enrichment Analysis
ego2.2 <- gseGO(geneList     = res.geneList,
              OrgDb        = org.Mm.eg.db,
              keyType      = "ENTREZID",
              ont          = "CC",
              nPerm        = 10000,                     #10k in real life
              minGSSize    = 50,                       #5-50 in real life
              maxGSSize    = 3000,                     #>2500 in real life
              pvalueCutoff = 0.05,                      #0.05 in real life (usually)
              verbose      = FALSE)

#writing to csv file 
DEG_gseGO_CC = write.csv(data.frame(ego2.2), "DEG_gseGO_CC.csv")


# GO-MF Gene Set Enrichment Analysis
ego2.3 <- gseGO(geneList     = res.geneList,
              OrgDb        = org.Mm.eg.db,
              keyType      = "ENTREZID",
              ont          = "MF",
              nPerm        = 10000,                     #10k in real life
              minGSSize    = 50,                       #5-50 in real life
              maxGSSize    = 3000,                     #>2500 in real life
              pvalueCutoff = 0.05,                      #0.05 in real life (usually)
              verbose      = FALSE)

#writing to csv file 
DEG_gseGO_MF = write.csv(data.frame(ego2.3), "DEG_gseGO_MF.csv")

# GO Gene Set Enrichment Analysis (with p-value =0.05)
ego2 <- gseGO(geneList     = res.geneList,
              OrgDb        = org.Mm.eg.db,
              keyType      = "ENTREZID",
              ont          = "ALL",
              nPerm        = 10000,                     #10k in real life
              minGSSize    = 50,                       #5-50 in real life
              maxGSSize    = 3000,                     #>2500 in real life
              pvalueCutoff = 0.05,                      #0.05 in real life (usually)
              verbose      = FALSE)

# write results to file
#write.table(ego2@result, file = paste(Sys.Date(),"eWAT_GSEA_Analysis.txt", sep = "_"), quote = F, sep = "\t")

#writing to csv file 
DEG_gseGO = write.csv(data.frame(ego2), "DEG_gseGO_ALL.csv")

head(ego2)

# GSEA plot of top significant BP pathways(p value =0.05)
par(mfrow=c(2,2))
gseaplot(ego2.1, geneSetID = "GO:0006355", 
         title = "GO:0006355 regulation of transcription, DNA-templated")
gseaplot(ego2.1, geneSetID = "GO:0006793", 
         title = "GO:0006793 phosphorus metabolic process")
gseaplot(ego2.1, geneSetID = "GO:0006796", 
         title = "GO:0006796 phosphate-containing compound metabolic process")
gseaplot(ego2.1, geneSetID = "GO:0009892", 
         title = "GO:0009892 negative regulation of metabolic process")
gseaplot(ego2.1, geneSetID = "GO:0033036", 
         title = "GO:0033036 macromolecule localization")
par(mfrow=c(1,1))

# dotplot split by direction of change
require(DOSE)

pdf(paste(Sys.Date(),"GSEA_dotplot_Split_by_sign.pdf", sep = "_"), width = 10)
dotplot(ego2,  title = "Significant GO ALL terms", split=".sign") + facet_grid(.~.sign)
dev.off()

pdf(paste(Sys.Date(),"GSEA_BP_dotplot_Split_by_sign.pdf", sep = "_"), width = 10)
dotplot(ego2.1,  title = "Significant GO BP terms", split=".sign") + facet_grid(.~.sign)
dev.off()

pdf(paste(Sys.Date(),"GSEA_CC_dotplot_Split_by_sign.pdf", sep = "_"), width = 10)
dotplot(ego2.2,  title = "Significant GO CC terms", split=".sign") + facet_grid(.~.sign)
dev.off()

pdf(paste(Sys.Date(),"GSEA_MF_dotplot_Split_by_sign.pdf", sep = "_"), width = 10)
dotplot(ego2.3,  title = "Significant GO MF terms", split=".sign") + facet_grid(.~.sign)
dev.off()

#cnetplot
pdf(paste(Sys.Date(),"GSEA_cnetplot.pdf", sep = "_"), width = 10)
cnetplot(ego2, categorySize="pvalue", foldChange=res.geneListFC) #categorySize can be scaled by 'pvalue' or 'geneNumber
dev.off()

#cnetplot of GO-BP interaction network
pdf(paste(Sys.Date(),"GSEA_BP_cnetplot.pdf", sep = "_"), width = 10)
cnetplot(ego2.1, categorySize="pvalue", foldChange=res.geneListFC) #categorySize can be scaled by 'pvalue' or 'geneNumber
dev.off()

#cnetplot of GO-CC interaction network
pdf(paste(Sys.Date(),"GSEA_CC_cnetplot.pdf", sep = "_"), width = 10)
cnetplot(ego2.2, categorySize="pvalue", foldChange=res.geneListFC) #categorySize can be scaled by 'pvalue' or 'geneNumber
dev.off()

#cnetplot of GO-MF interaction network
pdf(paste(Sys.Date(),"GSEA_MF_cnetplot.pdf", sep = "_"), width = 10)
cnetplot(ego2.3, categorySize="pvalue", foldChange=res.geneListFC) #categorySize can be scaled by 'pvalue' or 'geneNumber
dev.off()

# KEGG Gene Set Enrichment Analysis
kk2 <- gseKEGG(geneList     = res.geneList,
               organism     = 'mmu',
               keyType      = 'ncbi-geneid',
               nPerm        = 10000,
               pvalueCutoff = 0.05,
               verbose      = FALSE)

# write results to file
#write.table(kk2@result, file = paste(Sys.Date(),"KEGG_eWAT_GSEA_Analysis.txt", sep = "_"), quote = F, sep = "\t")

#writing to csv file
DEG_gseKEGG = write.csv(data.frame(kk2), "DEG_gseKEGG.csv")

head(kk2)

# GSEA plot of top significant pathways in KEGG

gseaplot(kk2, geneSetID = "mmu03013", title = "RNA transport")
gseaplot(kk2, geneSetID = "mmu05417", title = "Lipid and atherosclerosis")
gseaplot(kk2, geneSetID = "mmu04060", title = "Cytokine-cytokine receptor interaction")
gseaplot(kk2, geneSetID = "mmu05206", title = "MicroRNAs in cancer")
gseaplot(kk2, geneSetID = "mmu04668", title = "TNF signaling pathway")

# pathway viewing 
browseKEGG(kk, 'mmu03013') #View the KEGG pathway in web browser


#dotplot of KEGG pathway, split by direction of change

require(DOSE)

pdf(paste(Sys.Date(),"KEGG_GSEA_dotplot_Split_by_sign.pdf", sep = "_"), width = 10)
dotplot(kk2,  title = "Significant KEGG pathways", split=".sign") + facet_grid(.~.sign)
dev.off()


#cnetplot
pdf(paste(Sys.Date(),"KEGG_GSEA_cnetplot.pdf", sep = "_"), width = 10)
cnetplot(kk2, categorySize="pvalue", foldChange=res.geneListFC) #categorySize can be scaled by 'pvalue' or 'geneNumber
dev.off()

```

#heatmap

```{r heatmap, echo=FALSE}

############################################################################################# 6. Heatmap of deferentially expressed genes
#############################################################################################

### get the heatmap of aging changes at FDR5
## exclude NA
my.sig_res <- res[!is.na(res$padj),]
genes.eWAT <- rownames(my.sig_res)[my.sig_res$padj < 0.05] # FDR < 5%
my.num.eWAT <- length(genes.eWAT)
my.num.eWAT

# heatmap drawing 
library('pheatmap')
my.heatmap.out <- paste(Sys.Date(),"GSE154832_YOUNGvsAGE_Heatmap_significant_genes.pdf",sep="_")

pdf(my.heatmap.out, height = 10, width = 5, onefile = F)
my.heatmap.title <- paste("YOUNGvsAGED_significant (FDR < 5%), ",my.num.eWAT, " genes",sep="")

pheatmap(vsd[genes.eWAT,],
         cluster_cols = F,
         cluster_rows = T,
         colorRampPalette(rev(c("#CC3333","#FF9999","#FFCCCC","white","#CCCCFF","#9999FF","#333399")))(50),
         show_rownames = F, scale="row",
         main = my.heatmap.title, cellwidth = 30)
dev.off()

```


##session info
```{r sessioninfo, echo=FALSE}

# get all the relevant info on loaded packages
sessionInfo()

# one way to save that info for when you write up your paper
# with correct package versions
sink(file = paste(Sys.Date(),"_session_Info.txt", sep =""))
sessionInfo()
sink()

```

##THE END
